#!/usr/bin/env node
// Generates the static site from data/*.json and src/pages/*.html.
//   node tools/build.mjs          write the pages
//   node tools/build.mjs --check  fail if any generated page is out of date
// No dependencies; the output is plain HTML that GitHub Pages serves as is.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const site = JSON.parse(readFileSync(join(ROOT, 'data/site.json'), 'utf8'));
const data = JSON.parse(readFileSync(join(ROOT, 'data/projects.json'), 'utf8'));
const YEAR = '2026';

// ---------- i18n ----------
// Every visible string is a { locale: text } object. A missing translation is
// a build error rather than a silent fallback to another language.
function makeT(locale) {
  return (v, where = '') => {
    if (v == null) return v;
    if (typeof v === 'string' || Array.isArray(v)) return v;
    if (!(locale in v)) throw new Error(`Missing "${locale}" text ${where}: ${JSON.stringify(v).slice(0, 80)}`);
    return v[locale];
  };
}

// ---------- helpers ----------
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const attr = esc;

const ICONS = {
  arrow: '<path d="M11.3 3.3 10.6 4l3.5 3.5H1v1h13.1l-3.5 3.5.7.7L16 8z"/>',
  back: '<path d="M4.7 3.3 5.4 4 1.9 7.5H15v1H1.9l3.5 3.5-.7.7L0 8z"/>',
  external: '<path d="M13 14H3a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h5v1H3v10h10V8h1v5a1 1 0 0 1-1 1z"/><path d="M10 1v1h3.3L8.6 6.7l.7.7L14 2.7V6h1V1z"/>',
  download: '<path d="M13 7 12.3 6.3 8.5 10.1V1h-1v9.1L3.7 6.3 3 7l5 5z"/><path d="M13 12v2H3v-2H2v2a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1v-2z"/>',
  print: '<path d="M13 5h-1V1H4v4H3a2 2 0 0 0-2 2v5h3v3h8v-3h3V7a2 2 0 0 0-2-2zM5 2h6v3H5zm6 12H5V9h6zm3-3h-2V8H4v3H2V7a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1z"/>',
  info: '<path d="M8.5 11V6.5h-2v1h1V11H6v1h4v-1zM8 3.5a.75.75 0 1 0 .75.75A.75.75 0 0 0 8 3.5z"/><path d="M8 15a7 7 0 1 1 7-7 7 7 0 0 1-7 7zm0-13a6 6 0 1 0 6 6 6 6 0 0 0-6-6z"/>',
  add: '<path d="M8.5 7.5V3h-1v4.5H3v1h4.5V13h1V8.5H13v-1z"/>',
  code: '<path d="m15 8-4 4-.7-.7L13.6 8l-3.3-3.3.7-.7zM1 8l4-4 .7.7L2.4 8l3.3 3.3L5 12zM6.4 13.3l2.3-11 1 .2-2.3 11z"/>',
  menu: '<path d="M2 12h12v1H2zm0-4.5h12v1H2zM2 3h12v1H2z"/>'
};
function icon(name, cls = '') {
  const p = ICONS[name];
  if (!p) throw new Error(`Unknown icon ${name}`);
  const flip = name === 'arrow' || name === 'back' ? ' icon-flip' : '';
  return `<svg class="icon${flip}${cls ? ' ' + cls : ''}" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" focusable="false">${p}</svg>`;
}

// ---------- layout ----------
function layout(ctx, page) {
  const { t, s, locale } = ctx;
  const L = site.locales[locale];
  const depth = page.path.split('/').length - 1;
  const r = page.absolute ? site.basePath : '../'.repeat(depth);
  const canonicalPath = page.path.replace(/(^|\/)index\.html$/, '$1');
  const canonical = site.siteUrl + canonicalPath;
  const name = t(site.person.name);
  const fullTitle = page.title ? `${page.title} — ${name}` : `${name} — ${t(site.person.descriptor)}`;
  const nav = [
    ['projects', s.navProjects, 'projects/'],
    ['cv', s.navCv, 'cv.html'],
    ['certificates', s.navCertificates, 'certificates.html'],
    ['contact', s.navContact, 'index.html#contact']
  ];
  const navHtml = nav.map(([key, label, href]) =>
    `<li><a href="${r}${href}"${page.nav === key ? ' aria-current="page"' : ''}>${esc(label)}</a></li>`).join('');
  const scripts = ['assets/js/site.js', ...(page.scripts || [])].map((src) => `<script src="${r}${src}" defer></script>`).join('\n');
  const ogImage = site.siteUrl + 'assets/img/og.png';

  let body = page.body.replaceAll('{{root}}', r);

  return `<!DOCTYPE html>
<!-- Generated by tools/build.mjs from data/ and src/pages/. Edit those, not this file. -->
<html lang="${L.lang}" dir="${L.dir}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(fullTitle)}</title>
<meta name="description" content="${attr(page.description)}">
${page.noindex ? '<meta name="robots" content="noindex">' : `<link rel="canonical" href="${attr(canonical)}">`}
<meta property="og:type" content="${page.path === 'index.html' ? 'profile' : 'website'}">
<meta property="og:title" content="${attr(fullTitle)}">
<meta property="og:description" content="${attr(page.description)}">
<meta property="og:url" content="${attr(canonical)}">
<meta property="og:image" content="${attr(ogImage)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${attr(name + ' — ' + t(site.person.descriptor))}">
<meta name="twitter:card" content="summary_large_image">
<meta name="theme-color" content="#161616">
<link rel="icon" href="${r}assets/img/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="${r}assets/img/apple-touch-icon.png">
<link rel="preload" href="${r}assets/fonts/IBMPlexSans-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="${r}assets/css/fonts.css">
<link rel="stylesheet" href="${r}assets/css/site.css">
<script>document.documentElement.classList.add('js')</script>
${page.head || ''}</head>
<body${page.bodyClass ? ` class="${page.bodyClass}"` : ''} data-site-name="${attr(name)}">
<a class="skip-link" href="#main">${esc(s.skip)}</a>
<header class="site-header">
  <div class="container site-header__inner">
    <a class="brand" href="${r}index.html"><span class="brand__mark" aria-hidden="true">AA</span><span class="brand__name">${esc(name)}</span></a>
    <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav">${icon('menu')}<span>${esc(s.menu)}</span></button>
    <nav class="nav" id="site-nav" aria-label="Main"><ul>${navHtml}</ul></nav>
  </div>
</header>
<main id="main" tabindex="-1">
${body}
</main>
<footer class="site-footer">
  <div class="container site-footer__inner">
    <p>© ${YEAR} ${esc(name)}</p>
    <p>${esc(s.footerNote)}</p>
  </div>
</footer>
${scripts}
</body>
</html>
`;
}

function breadcrumb(ctx, items, r) {
  const { s } = ctx;
  const li = [`<li><a href="${r}index.html">${esc(s.home)}</a></li>`].concat(items.map(([label, href]) =>
    href ? `<li><a href="${r}${href}">${esc(label)}</a></li>` : `<li aria-current="page">${esc(label)}</li>`));
  return `<nav class="breadcrumb" aria-label="Breadcrumb"><ol>${li.join('')}</ol></nav>`;
}

function picture(img, r, alt, { sizes = '100vw', eager = false } = {}) {
  const srcset = img.srcset.split(',').map((p) => r + p.trim()).join(', ');
  const src = r + (img.fallback || img.src);
  return `<picture><source type="image/webp" srcset="${srcset}" sizes="${sizes}"><img src="${src}" width="${img.width}" height="${img.height}" alt="${attr(alt)}"${eager ? ' fetchpriority="high"' : ' loading="lazy"'} decoding="async"></picture>`;
}

// ---------- components ----------
function projectCard(ctx, p, r, headingLevel = 3) {
  const { t, s } = ctx;
  const status = t(data.statuses[p.status], p.slug);
  const tags = p.technologies.slice(0, 3).map((x) => `<li class="tag">${esc(x)}</li>`).join('');
  return `<li><article class="card">
  <div class="card__media">${picture(p.image, r, t(p.image.alt), { sizes: '(min-width: 66rem) 33vw, (min-width: 42rem) 50vw, 100vw' })}</div>
  <div class="card__body">
    <p class="card__meta">${esc(status)} · ${esc(p.year)}</p>
    <h${headingLevel} class="card__title"><a href="${r}projects/${p.slug}/">${esc(t(p.title))}</a></h${headingLevel}>
    <p class="card__summary">${esc(t(p.summary))}</p>
    <ul class="tags" aria-label="${attr(s.technologies)}">${tags}</ul>
    <div class="card__foot"><span class="card__cta" aria-hidden="true">${esc(s.readCaseStudy)} ${icon('arrow')}</span></div>
  </div>
</article></li>`;
}

// ---------- pages ----------
function homePage(ctx) {
  const { t, s } = ctx;
  const r = '';
  const featured = data.projects.filter((p) => p.featured);
  const focus = site.focus.map((f, i) => `<li><span class="num">0${i + 1}</span><h3 class="h3">${esc(t(f.title))}</h3><p>${esc(t(f.text))}</p></li>`).join('');
  const contact = site.contact.map((c) => `<li><a href="${attr(c.href)}"${c.external ? ' target="_blank" rel="noopener noreferrer"' : ''}><span class="k">${esc(t(c.label))}</span><span class="v">${esc(t(c.text))}${c.external ? `<span class="visually-hidden"> (${esc(s.externalLink)})</span>` : ''}</span>${icon(c.external ? 'external' : 'arrow')}</a></li>`).join('');
  const body = `<section class="hero" aria-labelledby="hero-title">
  <div class="container hero__grid">
    <div>
      <p class="eyebrow">${esc(t(site.person.descriptor))}</p>
      <h1 class="display" id="hero-title">${esc(t(site.person.name))}</h1>
      <p class="lead">${esc(t(site.person.intro))}</p>
      <div class="btn-row" style="margin-block-start: var(--sp-8)">
        <a class="btn btn--primary" href="projects/">${esc(s.viewProjects)} ${icon('arrow')}</a>
        <a class="btn btn--tertiary" href="cv.html">${esc(s.viewCv)} ${icon('arrow')}</a>
      </div>
    </div>
    <div class="hero__media">${picture(site.person.portrait, r, t(site.person.portrait.alt), { sizes: '(min-width: 66rem) 26rem, 18rem', eager: true })}</div>
  </div>
</section>

<section class="section" aria-labelledby="focus-title">
  <div class="container">
    <div class="section__head"><h2 class="h2" id="focus-title">${esc(s.focusHeading)}</h2></div>
    <ul class="focus-grid">${focus}</ul>
  </div>
</section>

<section class="section section--layer" aria-labelledby="work-title">
  <div class="container">
    <div class="section__head">
      <h2 class="h2" id="work-title">${esc(s.selectedWork)}</h2>
      <a class="link-arrow" href="projects/">${esc(s.allProjects)} (${data.projects.length}) ${icon('arrow')}</a>
    </div>
    <ul class="card-grid card-grid--3">${featured.map((p) => projectCard(ctx, p, r)).join('\n')}</ul>
  </div>
</section>

<section class="section" aria-labelledby="cred-title">
  <div class="container two-col">
    <h2 class="h2" id="cred-title">${esc(s.credentialsHeading)}</h2>
    <ul class="link-list">
      <li><a href="viewer.html?doc=fmva"><span class="k">CFI</span><span class="v">FMVA® — Financial Modeling &amp; Valuation Analyst</span>${icon('arrow')}</a></li>
      <li><a href="cv.html"><span class="k">CV</span><span class="v">Curriculum vitae</span>${icon('arrow')}</a></li>
      <li><a href="references.html"><span class="k">References</span><span class="v">Recommendation letters</span>${icon('arrow')}</a></li>
    </ul>
  </div>
</section>

<section class="section" id="contact" aria-labelledby="contact-title">
  <div class="container two-col">
    <div>
      <h2 class="h2" id="contact-title">${esc(s.contactHeading)}</h2>
      <p class="muted">${esc(s.contactText)}</p>
    </div>
    <ul class="link-list">${contact}</ul>
  </div>
</section>`;
  const personLd = {
    '@context': 'https://schema.org', '@type': 'Person', name: t(site.person.name), url: site.siteUrl,
    sameAs: site.contact.filter((c) => c.id === 'linkedin').map((c) => c.href)
  };
  return {
    path: 'index.html', title: null, nav: null, body,
    description: `${t(site.person.name)} — ${t(site.person.descriptor)}. ${t(site.person.intro)}`,
    head: `<script type="application/ld+json">${JSON.stringify(personLd)}</script>\n`
  };
}

function projectsPage(ctx) {
  const { t, s } = ctx;
  const r = '../';
  const groups = Object.keys(data.statuses).map((key) => {
    const items = data.projects.filter((p) => p.status === key);
    if (!items.length) return '';
    return `<section class="group" aria-labelledby="g-${key}">
  <h2 class="group__title"><span class="h3" style="margin:0" id="g-${key}">${esc(t(data.statuses[key]))}</span><span class="group__count">${items.length}</span></h2>
  <ul class="card-grid card-grid--3">${items.map((p) => projectCard(ctx, p, r)).join('\n')}</ul>
</section>`;
  }).join('\n');
  const body = `<div class="container">
  <header class="page-head">
    ${breadcrumb(ctx, [[s.projectsTitle, null]], r)}
    <h1 class="h1">${esc(s.projectsTitle)}</h1>
    <p class="lead">${esc(s.projectsIntro)}</p>
  </header>
  ${groups}
</div>`;
  return { path: 'projects/index.html', title: s.projectsTitle, nav: 'projects', body, description: s.projectsIntro };
}

function projectPage(ctx, p, i) {
  const { t, s } = ctx;
  const r = '../../';
  const list = data.projects;
  const prev = list[(i - 1 + list.length) % list.length];
  const next = list[(i + 1) % list.length];
  const buttons = [];
  if (p.links.demo) buttons.push(`<a class="btn btn--primary" href="${r}${p.links.demo}">${esc(s.openDemo)} ${icon('arrow')}</a>`);
  if (p.links.live) buttons.push(`<a class="btn btn--primary" href="${attr(p.links.live)}" target="_blank" rel="noopener noreferrer">${esc(s.openDemo)}<span class="visually-hidden"> (${esc(s.externalLink)})</span> ${icon('external')}</a>`);
  if (p.links.source) buttons.push(`<a class="btn btn--tertiary" href="${attr(p.links.source)}" target="_blank" rel="noopener noreferrer">${esc(s.viewSource)}<span class="visually-hidden"> (${esc(s.externalLink)})</span> ${icon('code')}</a>`);
  const section = (id, title, html) => html ? `<section class="case-section" aria-labelledby="${id}"><h2 class="h3" id="${id}">${esc(title)}</h2>${html}</section>` : '';
  const features = t(p.features, p.slug);
  let family = '';
  if (p.family) {
    const fam = data.families[p.family];
    if (!fam) throw new Error(`${p.slug}: unknown family ${p.family}`);
    const siblings = list.filter((x) => x.family === p.family && x.slug !== p.slug)
      .map((x) => `<a class="link" href="${r}projects/${x.slug}/">${esc(t(x.title))}</a>`).join(', ');
    family = `<div><dt>${esc(s.partOf)}</dt><dd>${esc(t(fam.name))}${siblings ? `<br><span class="muted">${esc(s.alsoIn)} ${siblings}</span>` : ''}</dd></div>`;
  }
  const body = `<div class="container">
  <header class="page-head">
    ${breadcrumb(ctx, [[s.projectsTitle, 'projects/'], [t(p.title), null]], r)}
    <p class="eyebrow">${esc(t(p.type))}</p>
    <h1 class="h1">${esc(t(p.title))}</h1>
    <p class="lead">${esc(t(p.summary))}</p>
    ${buttons.length ? `<div class="btn-row" style="margin-block-start: var(--sp-7)">${buttons.join('')}</div>` : ''}
  </header>
  ${p.notice ? `<div class="notice" role="note">${icon('info')}<p>${esc(t(p.notice))}</p></div>` : ''}
  <figure class="figure">
    <div class="figure__frame">${picture(p.image, r, t(p.image.alt), { sizes: '(min-width: 82rem) 78rem, 100vw', eager: true })}</div>
    <figcaption>${esc(t(p.image.caption))}</figcaption>
  </figure>
  <div class="case-grid">
    <aside>
      <dl class="meta-list">
        <div><dt>${esc(s.type)}</dt><dd>${esc(t(p.type))}</dd></div>
        <div><dt>${esc(s.status)}</dt><dd>${esc(t(data.statuses[p.status]))}</dd></div>
        <div><dt>${esc(s.year)}</dt><dd>${esc(p.year)}</dd></div>
        ${family}
        <div><dt>${esc(s.technologies)}</dt><dd><ul class="tags">${p.technologies.map((x) => `<li class="tag">${esc(x)}</li>`).join('')}</ul></dd></div>
      </dl>
    </aside>
    <div class="prose">
      ${section('problem', s.problem, p.problem ? `<p>${esc(t(p.problem))}</p>` : '')}
      ${section('features', s.whatItDoes, `<ul class="feature-list">${features.map((f) => `<li>${esc(f)}</li>`).join('')}</ul>`)}
      ${section('role', s.myRole, p.role ? `<p>${esc(t(p.role))}</p>` : '')}
      ${section('outcome', s.outcome, p.outcome ? `<p>${esc(t(p.outcome))}</p>` : '')}
    </div>
  </div>
  <nav class="pager" aria-label="More projects" style="margin-block-start: var(--sp-10)">
    <a href="${r}projects/${prev.slug}/"><span class="label">${esc(s.previous)}</span><span class="title">${esc(t(prev.title))}</span></a>
    <a class="next" href="${r}projects/${next.slug}/"><span class="label">${esc(s.next)}</span><span class="title">${esc(t(next.title))}</span></a>
  </nav>
</div>`;
  return { path: `projects/${p.slug}/index.html`, title: t(p.title), nav: 'projects', body, description: t(p.summary) };
}

function partialPages(ctx) {
  const dir = join(ROOT, 'src/pages');
  return readdirSync(dir).filter((f) => f.endsWith('.html')).sort().map((f) => {
    const raw = readFileSync(join(dir, f), 'utf8');
    const m = raw.match(/^<!--meta\s*([\s\S]*?)-->\s*/);
    if (!m) throw new Error(`${f}: missing <!--meta … --> block`);
    const meta = JSON.parse(m[1]);
    const depth = meta.path.split('/').length - 1;
    const r = meta.absolute ? site.basePath : '../'.repeat(depth);
    let body = raw.slice(m[0].length);
    body = body.replace('{{breadcrumb}}', meta.breadcrumb ? breadcrumb(ctx, meta.breadcrumb, r) : '');
    body = body.replace(/\{\{icon:([a-z]+)\}\}/g, (_, n) => icon(n));
    body = body.replace('{{doc-allowlist}}', () => docAllowlist(ctx));
    return { ...meta, body };
  });
}

function docAllowlist(ctx) {
  const { t } = ctx;
  const docs = {};
  for (const [id, d] of Object.entries(site.documents)) {
    if (!existsSync(join(ROOT, d.file))) throw new Error(`Document ${id} points to a missing file: ${d.file}`);
    docs[id] = { file: d.file, title: t(d.title), back: d.back };
  }
  return `<script type="application/json" id="doc-allowlist">${JSON.stringify(docs).replace(/</g, '\\u003c')}</script>`;
}

// 404: GitHub Pages serves this for any missing path under the site, so it
// uses absolute URLs and redirects old or differently-cased links to the
// canonical page. Only targets from this table are ever used.
function notFoundPage(ctx, allPaths) {
  const legacy = {
    'resources/referances.pdf': 'Resources/References.pdf',
    'resources/fmva.pdf': 'Resources/Certificates/FMVA.pdf',
    'certificates/fmva.pdf': 'Resources/Certificates/FMVA.pdf',
    'resources/cv.html': 'cv.html'
  };
  for (let n = 1; n <= 5; n++) {
    legacy[`resources/references/recommendation${n}.pdf`] = 'references.html';
    legacy[`resources/recommendations/recommendation${n}.pdf`] = 'references.html';
  }
  const map = { ...legacy };
  for (const p of allPaths) {
    const clean = p.replace(/(^|\/)index\.html$/, '$1');
    map[p.toLowerCase()] = clean;
    map[clean.toLowerCase()] = clean;
    if (clean.endsWith('/')) map[clean.slice(0, -1).toLowerCase()] = clean;
    if (p.endsWith('.html')) map[p.slice(0, -5).toLowerCase()] = clean;
  }
  const body = `<div class="container">
  <header class="page-head">
    <p class="eyebrow">404</p>
    <h1 class="h1">Page not found</h1>
    <p class="lead">The page may have moved. These links cover everything on the site:</p>
  </header>
  <ul class="link-list">
    <li><a href="${site.basePath}"><span class="k">Home</span><span class="v">${esc(ctx.t(site.person.name))}</span>${icon('arrow')}</a></li>
    <li><a href="${site.basePath}projects/"><span class="k">Projects</span><span class="v">All projects</span>${icon('arrow')}</a></li>
    <li><a href="${site.basePath}cv.html"><span class="k">CV</span><span class="v">Curriculum vitae</span>${icon('arrow')}</a></li>
    <li><a href="${site.basePath}certificates.html"><span class="k">Certificates</span><span class="v">Certificates</span>${icon('arrow')}</a></li>
  </ul>
</div>
<script>
(function () {
  var base = ${JSON.stringify(site.basePath)};
  var map = ${JSON.stringify(map)};
  var path = location.pathname;
  if (path.toLowerCase().indexOf(base.toLowerCase()) !== 0) return;
  var rel;
  try { rel = decodeURIComponent(path.slice(base.length)); } catch (e) { return; }
  var key = rel.toLowerCase().replace(/\\/index\\.html$/, '/');
  var target = Object.prototype.hasOwnProperty.call(map, key) ? map[key] : null;
  if (target !== null && base + target !== path) location.replace(base + target + location.search + location.hash);
})();
</script>`;
  return { path: '404.html', absolute: true, title: 'Page not found', noindex: true, body, description: 'Page not found.' };
}

// ---------- run ----------
function build(locale) {
  const t = makeT(locale);
  const s = site.strings[locale];
  if (!s) throw new Error(`No UI strings for locale ${locale}`);
  const ctx = { t, s, locale };
  const slugs = new Set();
  for (const p of data.projects) {
    if (!/^[a-z0-9-]+$/.test(p.slug) || slugs.has(p.slug)) throw new Error(`Bad or duplicate slug: ${p.slug}`);
    slugs.add(p.slug);
    if (!data.statuses[p.status]) throw new Error(`${p.slug}: unknown status ${p.status}`);
    for (const k of ['title', 'type', 'summary', 'features']) t(p[k], `${p.slug}.${k}`);
    for (const src of p.image.srcset.split(',').map((x) => x.trim().split(' ')[0])) {
      if (!existsSync(join(ROOT, src))) console.warn(`warning: ${p.slug} image missing: ${src}`);
    }
  }
  const pages = [homePage(ctx), projectsPage(ctx), ...data.projects.map((p, i) => projectPage(ctx, p, i)), ...partialPages(ctx)];
  const paths = new Set(pages.map((p) => p.path));
  for (const p of data.projects) {
    if (p.links.demo && !paths.has(p.links.demo + 'index.html')) throw new Error(`${p.slug}: demo page ${p.links.demo} is not built from src/pages`);
  }
  const resources = ['Resources/References.pdf', 'Resources/Certificates/FMVA.pdf'];
  pages.push(notFoundPage(ctx, pages.map((p) => p.path).concat(resources)));
  return pages.map((p) => ({ path: p.path, html: layout(ctx, p), noindex: p.noindex }));
}

const out = build(site.defaultLocale);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${out.filter((p) => !p.noindex).map((p) => `  <url><loc>${site.siteUrl}${p.path.replace(/(^|\/)index\.html$/, '$1')}</loc></url>`).join('\n')}
</urlset>
`;
out.push({ path: 'sitemap.xml', html: sitemap });

let stale = 0;
for (const { path, html } of out) {
  const file = join(ROOT, path);
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (CHECK) {
    if (current !== html) { console.error(`out of date: ${path}`); stale++; }
    continue;
  }
  if (current !== html) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, html);
    console.log(`wrote ${relative(ROOT, file)}`);
  }
}
if (CHECK) {
  if (stale) { console.error(`${stale} generated file(s) out of date — run node tools/build.mjs`); process.exit(1); }
  console.log(`all ${out.length} generated files up to date`);
}
